---
title: "3_AdditionalPlots"
author: "Aimara Planillo"
date: "11/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Additional plots


# Study area map

```{r}
# Nachtigall project records
nightingales_2018 <- read.csv(paste0(procdata_wd, "/Nachtigall_project/Nightingales_corrected_2018_maxent.csv")) %>%
  st_as_sf(coords = c("X", "Y"), crs = 25833)

# eBird records
eBird_presences_2018 <- read.csv(paste0(procdata_wd, "/eBird/ebd_marjul_201718_nightingale_all_presences.csv")) %>%
  mutate(year = year(observation_date)) %>%
  filter(year == 2018) %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326) %>%
  st_transform(crs = 25833)

# Standardized data 
nightingales_quadrants <- read_sf(paste0(rawdata_wd, "/EnvCov/birds_quadrants1x1km_3035.gpkg"))
plot(st_geometry(nightingales_quadrants))

# berlin context
berlin <- read_sf(paste0(rawdata_wd, "/EnvCov/berlin_city_border_25833.gpkg"), crs = 25833) %>%
  st_union()
water <- read_sf(paste0(rawdata_wd, "/EnvCov/waterbodies_Berlin_25833.gpkg"))
land_use <- read_sf(paste0(procdata_wd, "/berlin_LandUse_modified_32633.gpkg"),
                    crs = 32633) %>% st_transform(crs = 25833)

# give color to the land use classes 
land_use1 <- land_use %>%
  st_transform(3035)
plot(st_geometry(land_use1))
unique(land_use1$Class2)
palette_landuse <- c('tan', '#FFFFCC', 'forestgreen', '#66FF99', 'grey50', 
                     '#00CC66', 'indianred3', 'orangered4', '#0066CC')

# get proper format
nightingales_quadrants1 <- st_transform(nightingales_quadrants, crs = 3035)

water1 <- st_transform(water, crs = 3035)

study_area_map <- tm_shape(land_use1) +
  tm_polygons(col = "Class2", palette = palette_landuse,
              border.col = NULL, alpha = 0.7,
            title = "Land use",
            style = "cont")+
  tm_shape(berlin) +
  tm_borders("ivory4", lwd = 2) +
  tm_shape(nightingales_2018) +
  tm_dots(size = 0.2, "black")+
  tm_shape(nightingales_quadrants1) +
  tm_borders(col = "darkblue", lwd = 2) +
  tm_shape(eBird_presences_2018) +
  tm_dots(size = 0.3, "red") +
  tm_layout(main.title = "Nightingale data", 
            compass.type = "arrow",
            legend.title.size = 0.8,
            legend.text.size = 0.6, 
          legend.bg.color = "white",
          legend.position = c("right", "top"),
            inner.margins = c(0.05,0.05,0.05,0.1),
          legend.frame = TRUE)+
  tm_add_legend(type = "line", labels = "Breeding birds transects", 
                lwd = 2, col = "darkblue")+
  tm_add_legend(type = "symbol", labels = "Nachtigall project", shape = 21, 
                size = 0.5, border.lwd = 0, col = "black")+
  tm_add_legend(type = "symbol", labels = "eBird", shape = 21, 
                size = 0.5, border.lwd = 0, col = "red")+
  tm_compass(position = c("right", "bottom"),
             size = 3) +
  tm_scale_bar(position=c("left", "bottom"), 
               size = 1)
```


```{r}
tmap_save(tm = study_area_map, filename = paste0(results_wd, "/Study_area_map.png"), 
          width = 8, height = 7, units = "in")
```



